<a href="https://colab.research.google.com/github/Chaitanya-Kk/Python-Viva/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# All required Fundamentals of Tensorflow

Topics Covered
* Introduction to Tensors
* Getting information from tensors
* Manupulating Tensors
* Tensos & Numpy
* Using @tf.function
* Using GPU with Tensor
* Exercises

In [ ]:
# Import TensorFlow
import tensorflow as tf
print("Tensorflow version", tf.__version__)

Tensorflow version 2.18.0


In [ ]:
#Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the number of dimensions of a tensor (.ndim)
scalar.ndim


0

In [ ]:
# Create a Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check dimensions of Vector
vector.ndim

1

In [ ]:
#Create a matrix (more than one dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix
another_matrix = tf.constant([[19.,11.],
                             [3.,2.],
                             [8.,10.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[19., 11.],
       [ 3.,  2.],
       [ 8., 10.]], dtype=float16)>

In [ ]:
#What's the number of dimensions of another_matrix
another_matrix.ndim

2

In [ ]:
#Let's Create a tensor
tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                       [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:
* Scalr: a single number
* vector: a number with direction
* Matrix: a 2 dimensional array of number
* Tensor an n-dimensional array of any number

### Creating tensors with tf.variable

In [19]:
#creating same tensor with tf.Variable
changeable_tensor = tf.Variable([19,11])
unchangeable_tensor = tf.constant([19,11])
changeable_tensor , unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([19, 11], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([19, 11], dtype=int32)>)

In [20]:
# Let's try change one of the elements in our changable tensor
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [21]:
# how about trying .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 11], dtype=int32)>

In [24]:
# Let's try change one of the elements in our unchangable tensor
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

🔑**Note**:Rarely in practice we need to decide Whether to use tf.constant or tf.Variable to create tensors as Tensorflow does this for you however if in doubt use tf.constant and change it later if needed

### Creating random tensors
random tensors are tensors of some abitrary size which contain random numbers

In [30]:
#Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(19) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(19)
random_2 = random_2.normal(shape =(3,2))

#are they equal
random_1,random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.06695071, -0.35105535],
        [ 1.0884082 , -1.3863064 ],
        [ 0.88051325, -1.6833194 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.06695071, -0.35105535],
        [ 1.0884082 , -1.3863064 ],
        [ 0.88051325, -1.6833194 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### shuffle the order of elements in a tensor

In [33]:
# Shuffle a tensor (valuable for when want to shuffle data so the inherent order dosne't affect learning)
not_shuffled = tf.constant([[10,7],
                            [11,14],
                            [19,2]])
# shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [19,  2],
       [11, 14]], dtype=int32)>

In [34]:
# shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 14],
       [19,  2],
       [10,  7]], dtype=int32)>

In [35]:
# shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[19,  2],
       [11, 14],
       [10,  7]], dtype=int32)>

In [36]:
# shuffle our non_shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [11, 14],
       [19,  2]], dtype=int32)>

In [37]:
# shuffle our non_shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [11, 14],
       [19,  2]], dtype=int32)>